export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';

export const FILTER_TASKS = 'FILTER_TASKS';
export const FILTER_TASKS_SUCCESS = 'FILTER_TASKS_SUCCESS';
